server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/market_dev?useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Seoul
    username: root
    password:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update